// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/resume": {
    params: {};
  };
  "/icons": {
    params: {};
  };
  "/rls": {
    params: {};
  };
  "/notes": {
    params: {};
  };
  "/notes/grpccode": {
    params: {};
  };
  "/notes/git": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/resume" | "/icons" | "/rls" | "/notes" | "/notes/grpccode" | "/notes/git";
  };
  "./layout/main-layout.tsx": {
    id: "layout/main-layout";
    page: "/" | "/contact" | "/resume" | "/icons" | "/rls" | "/notes" | "/notes/grpccode" | "/notes/git";
  };
  "./pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "./pages/contact.tsx": {
    id: "pages/contact";
    page: "/contact";
  };
  "./pages/resume.tsx": {
    id: "pages/resume";
    page: "/resume";
  };
  "./pages/icons.tsx": {
    id: "pages/icons";
    page: "/icons";
  };
  "./pages/rls.tsx": {
    id: "pages/rls";
    page: "/rls";
  };
  "./pages/notes.tsx": {
    id: "pages/notes";
    page: "/notes" | "/notes/grpccode" | "/notes/git";
  };
  "./pages/notes/index.tsx": {
    id: "pages/notes/index";
    page: "/notes";
  };
  "./pages/notes/grpccode.tsx": {
    id: "pages/notes/grpccode";
    page: "/notes/grpccode";
  };
  "./pages/notes/git.tsx": {
    id: "pages/notes/git";
    page: "/notes/git";
  };
};